#logging.pattern.console=%-4relative [%thread] %-5level %logger{35} - %X{CorrelationId} --- %msg %n
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
      username: root
      password: MongoDB2019!
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      authentication-database: admin